"""corrige nome da coluna

Revision ID: 7ff089d1cecb
Revises: d41db0ca12bb
Create Date: 2026-08-31 18:11:23.716012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff089d1cecb'
down_revision: Union[str, Sequence[str], None] = 'd41db0ca12bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_threshold', sa.Integer(), nullable=True))
    op.drop_column('users', 'temp_threshhold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_threshhold', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'temp_threshold')
    # ### end Alembic commands ###
