"""Adiciona campos color e style na tabela clothes

Revision ID: cfaef1fa2183
Revises: b69341eeb923
Create Date: 2026-08-31 17:22:47.837499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfaef1fa2183'
down_revision: Union[str, Sequence[str], None] = 'b69341eeb923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('color', sa.String(), nullable=True))
    op.add_column('clothes', sa.Column('style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'style')
    op.drop_column('clothes', 'color')
    # ### end Alembic commands ###
