"""Adiciona preferencia de temperatura no usuario

Revision ID: d41db0ca12bb
Revises: cfaef1fa2183
Create Date: 2026-08-31 17:57:26.981954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41db0ca12bb'
down_revision: Union[str, Sequence[str], None] = 'cfaef1fa2183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_threshhold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_threshhold')
    # ### end Alembic commands ###
