"""Adiciona suporte a imagens

Revision ID: d45da36a03a0
Revises: 7ff089d1cecb
Create Date: 2026-09-02 00:33:43.782574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45da36a03a0'
down_revision: Union[str, Sequence[str], None] = '7ff089d1cecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'image_url')
    # ### end Alembic commands ###
